language: c
compiler:
  - gcc
  - clang
install: 
    - sudo sh -c 'echo "deb http://mirrors.kernel.org/ubuntu trusty main" >> /etc/apt/sources.list'
    - sudo apt-get update
    - sudo apt-get install libglib2.0-dev libfuse-dev libcunit1-dev valgrind
    - make
    - fusermount -V
script: 
    - mount
    - make tests
    - make acc-test
