language: c
compiler:
  - gcc
  - clang
env:
    - PREFIX=/usr/local

install: 
    - sudo sh -c 'echo "deb http://mirrors.kernel.org/ubuntu trusty main" >> /etc/apt/sources.list'
    - sudo apt-get update
    - sudo apt-get install libglib2.0-dev libfuse-dev valgrind
    - svn co svn://svn.code.sf.net/p/cunit/code/trunk cunit
    - sudo depmod
    - cd cunit
    - ./bootstrap
    - make && sudo make install
    - cd ..
    - make
    - fusermount -V
    - sudo modprobe fuse
script: 
    - mount
    - make tests
    - make acc-test
