SUBFS_COMPONENTS = query tagdb
SUBFS_LSRCS = $(patsubst %, %.fs, $(SUBFS_COMPONENTS))
SUBFS_OBJS = $(patsubst %, %.fo, $(SUBFS_COMPONENTS))

.PHONY: subfs.c
components.l: $(SUBFS_LSRCS)
	$(LEX) $(SUBFS_LSRCS)
components.c: $(SUBFS_OBJS) components.l
	$(LEX) components.l ; rm components.l
subfs.o: OBJS+=$(SUBFS_OBJS) components.c

