#!/usr/bin/env perl

use Cwd;
{
    local $/ = undef;
    print "pid = $$\n";
    open(LISTEN, ">", "#LISTEN#");
    my $name=shift;
    print "TAG TSPEC /name=$name\n";
    print LISTEN "TAG TSPEC /name=$name";
    close(LISTEN);
    open(QR, "<", "#QREAD-$$#");
    $id = int(<QR>);
    while (<QR>) { print "doin it\n" }
    print "\"FILE ADD_TAGS $id " . join(" ", @ARGV) . "\"\n";
    open(LISTEN, ">", "#LISTEN#");
    print LISTEN "FILE ADD_TAGS $id " . join(" ", @ARGV);
    $result = int(<QR>);
    print "id = $id\n";
    print "result = $result\n";
    close(LISTEN);
    close(QR);
}
